### ISSUE TITLE
Clarify if web action or not

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-index-big-tree#6]
## Overview
The action is currently not deployed as webaction. 

if this is intended:
- fix the readme
- improve the status monitoring for non-webactions

if this is not intended:
- deploy it _properly_

**Comment by trieloff** [comment]
It is intended to be not a web action. Web actions come with shorter timeouts, and this action can be long running, especially for large repos.

**Comment by trieloff** [comment]
Still needs readme update.
